spring.application.name=user-service
server.port=8013
# Datasource Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/userdb
spring.datasource.username=embarkx
spring.datasource.password=embarkx

# JPA Configuration
spring.jpa.database=POSTGRESQL
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect






