spring.application.name=user-service
server.port=8015

spring.data.mongodb.uri=mongodb+srv://anupamshubhamdeoria_db_user:9C3dAlJnCVHBAHJk@user-data.dpf3xjm.mongodb.net/userdb?retryWrites=true&w=majority&appName=user-data
spring.data.mongodb.database=userdb

# spring.data.mongodb.uri=mongodb+srv://anupamshubhamdeoria_db_user:9C3dAlJnCVHBAHJk@user-data.dpf3xjm.mongodb.net/userdb

# Datasource Configuration
# spring.datasource.url=jdbc:postgresql://localhost:5432/userdb
# spring.datasource.username=embarkx
# spring.datasource.password=embarkx

# JPA Configuration
# spring.jpa.database=POSTGRESQL
# spring.jpa.show-sql=true
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect






